
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVL = 41;
  public static final int CAST = 11;
  public static final int LLAVD = 42;
  public static final int CONST = 9;
  public static final int CHAR = 5;
  public static final int ENTERO = 48;
  public static final int DIFERENTE = 27;
  public static final int DOUBLE = 3;
  public static final int RESTA = 20;
  public static final int CONTINUE = 18;
  public static final int INT = 2;
  public static final int MATCH = 13;
  public static final int MENOS_UNARIO = 36;
  public static final int NOT = 34;
  public static final int AND = 33;
  public static final int CARACTER = 51;
  public static final int IGUALDAD = 26;
  public static final int OR = 32;
  public static final int BOOL = 4;
  public static final int RAIZ = 24;
  public static final int INCREMENTO = 37;
  public static final int SUMA = 19;
  public static final int IF = 12;
  public static final int ID = 50;
  public static final int DECIMAL = 49;
  public static final int EOF = 0;
  public static final int TRUE = 7;
  public static final int DECREMENTO = 38;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int CADENA = 52;
  public static final int MODULO = 25;
  public static final int MENOR = 28;
  public static final int BREAK = 17;
  public static final int ASIGNACION = 35;
  public static final int MAYOR = 29;
  public static final int POTENCIA = 23;
  public static final int DOSPTOS = 47;
  public static final int PARL = 39;
  public static final int WHILE = 15;
  public static final int DEFAULT = 14;
  public static final int MAYOR_IGUAL = 31;
  public static final int CORL = 43;
  public static final int LET = 10;
  public static final int PARD = 40;
  public static final int PTCOMA = 45;
  public static final int STRING = 6;
  public static final int CORD = 44;
  public static final int MENOR_IGUAL = 30;
  public static final int FALSE = 8;
  public static final int DIVISION = 22;
  public static final int DO = 16;
  public static final int MULTIPLICACION = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "TRUE",
  "FALSE",
  "CONST",
  "LET",
  "CAST",
  "IF",
  "MATCH",
  "DEFAULT",
  "WHILE",
  "DO",
  "BREAK",
  "CONTINUE",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "RAIZ",
  "MODULO",
  "IGUALDAD",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "NOT",
  "ASIGNACION",
  "MENOS_UNARIO",
  "INCREMENTO",
  "DECREMENTO",
  "PARL",
  "PARD",
  "LLAVL",
  "LLAVD",
  "CORL",
  "CORD",
  "PTCOMA",
  "COMA",
  "DOSPTOS",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CARACTER",
  "CADENA"
  };
}

